filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /bdata/data/nowdb2/log/*.csv
  exclude_lines: [".+?08006[^*].+", ".+?08P01[^*].+"]
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
output.elasticsearch:
  hosts: ["XXXX:9200"]
  index: "XXXXX-%{+yyyy.MM.dd}"
  pipeline: "filebeat-7.6.2-postgresql-log-pipeline"
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.ilm.enabled: false
